### ISSUE TITLE
Implement Family Planning

### ISSUE THREAD

**Issue by cozej4** [Digital-Square-Tanzania/opensrp-client-chw#11]
![Image](https://github.com/Digital-Square-Tanzania/opensrp-client-chw/assets/9714534/1bc76085-89d4-4c10-90b2-17b6db4fdb5a)

[Family Planning](https://docs.google.com/spreadsheets/d/1dr8uhaF9KN09DzcQf6-l_VsC6jXCQ5ddj1cKnuymkto/edit#gid=285998844&range=A39)

**Comment by gosso22** [comment]
@cozej4 and @eddymathew - here there is some texts in data dictionary, that was not included. Are we adding those like below:

![Image](https://github.com/Digital-Square-Tanzania/opensrp-client-chw/assets/2742891/e36a7031-2f84-4b01-917a-66692942f95f)

Also - the start date there. Do we need to show start date even when Family Planning method chosen is none?
