### ISSUE TITLE
BUG (ADDO & CHW): The app does not allow sending multiple referrals for the same user

### ISSUE THREAD

**Issue by gosso22** [Digital-Square-Tanzania/opensrp-client-chw#63]

**Comment by gosso22** [comment]
We identified a bug in the server that is causing this. I am going to add @cozej4 here as he has started to look into this on the server side.

**Comment by cozej4** [comment]
Thank you for tagging me on this @gosso22 I share the updated WAR files and jar file dependencies before the end of the day.

**Comment by cozej4** [comment]
@gosso22 I have resolved the issue on the UCS staging environment. I'll also share the updated opensrp-server-core dependency libraries that should be deployed in the dev server to fix the issues.
